import { User, Post, TrendingTopic } from '@/types';

export const mockUsers: User[] = [
  {
    id: '1',
    username: 'rajesh_kumar',
    name: 'Rajesh Kumar',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=rajesh',
    bio: 'Tech enthusiast | Coffee lover | Building the future',
    followers: 1234,
    following: 567,
    verified: true,
  },
  {
    id: '2',
    username: 'priya_sharma',
    name: 'Priya Sharma',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=priya',
    bio: 'Designer | Artist | Mumbai',
    followers: 2345,
    following: 432,
    verified: false,
  },
  {
    id: '3',
    username: 'amit_patel',
    name: 'Amit Patel',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=amit',
    bio: 'Entrepreneur | Startup founder | Innovation',
    followers: 5678,
    following: 234,
    verified: true,
  },
  {
    id: '4',
    username: 'sneha_reddy',
    name: 'Sneha Reddy',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=sneha',
    bio: 'Food blogger | Travel enthusiast',
    followers: 3456,
    following: 789,
    verified: false,
  },
  {
    id: '5',
    username: 'vikram_singh',
    name: 'Vikram Singh',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=vikram',
    bio: 'Sports fan | Cricket lover | Delhi',
    followers: 890,
    following: 123,
    verified: false,
  },
];

export const mockPosts: Post[] = [
  {
    id: '1',
    content: 'Just launched our new startup! Excited to share this journey with all of you. Looking for early adopters and feedback. 🚀 #StartupIndia #Innovation',
    author: mockUsers[2],
    likes: 234,
    comments: 45,
    reposts: 12,
    views: 1234,
    timestamp: new Date(Date.now() - 2 * 60 * 60 * 1000),
    isLiked: false,
    isReposted: false,
    hashtags: ['StartupIndia', 'Innovation'],
  },
  {
    id: '2',
    content: 'Beautiful sunrise at Marine Drive this morning! Mumbai never fails to amaze me. 🌅\n\nSometimes you need to wake up early to witness nature\'s beauty.',
    author: mockUsers[1],
    likes: 567,
    comments: 89,
    reposts: 34,
    views: 2345,
    timestamp: new Date(Date.now() - 5 * 60 * 60 * 1000),
    isLiked: true,
    isReposted: false,
    images: ['https://picsum.photos/400/300?random=1'],
    hashtags: ['Mumbai', 'Sunrise', 'MarineDrive'],
  },
  {
    id: '3',
    content: 'Just completed a 30-day coding challenge! Learned so much about algorithms and data structures. Next goal: Contributing to open source projects. 💻 #CodingLife #TechTwitter',
    author: mockUsers[0],
    likes: 123,
    comments: 23,
    reposts: 8,
    views: 567,
    timestamp: new Date(Date.now() - 8 * 60 * 60 * 1000),
    isLiked: false,
    isReposted: false,
    hashtags: ['CodingLife', 'TechTwitter'],
  },
  {
    id: '4',
    content: 'Street food tour in Old Delhi was amazing! The parathas at Paranthe Wali Gali are to die for. 🍽️\n\nFood is not just about taste, it\'s about culture and memories.',
    author: mockUsers[3],
    likes: 890,
    comments: 156,
    reposts: 67,
    views: 3456,
    timestamp: new Date(Date.now() - 12 * 60 * 60 * 1000),
    isLiked: true,
    isReposted: true,
    images: ['https://picsum.photos/400/300?random=2', 'https://picsum.photos/400/300?random=3'],
    hashtags: ['DelhiFood', 'StreetFood', 'Foodie'],
  },
  {
    id: '5',
    content: 'India wins the match! What a performance by the team. Proud moment for all of us! 🏏🇮🇳 #Cricket #TeamIndia',
    author: mockUsers[4],
    likes: 1234,
    comments: 234,
    reposts: 123,
    views: 5678,
    timestamp: new Date(Date.now() - 24 * 60 * 60 * 1000),
    isLiked: false,
    isReposted: false,
    hashtags: ['Cricket', 'TeamIndia'],
  },
  {
    id: '6',
    content: 'Working from a beautiful co-working space in Bangalore today. The startup ecosystem here is incredible! Met some amazing founders. #BangaloreDiaries #StartupLife',
    author: mockUsers[2],
    likes: 345,
    comments: 56,
    reposts: 23,
    views: 1890,
    timestamp: new Date(Date.now() - 36 * 60 * 60 * 1000),
    isLiked: false,
    isReposted: false,
    hashtags: ['BangaloreDiaries', 'StartupLife'],
  },
];

export const mockTrending: TrendingTopic[] = [
  {
    id: '1',
    hashtag: '#IPL2024',
    posts: 12567,
    category: 'Sports',
  },
  {
    id: '2',
    hashtag: '#StartupIndia',
    posts: 8934,
    category: 'Business',
  },
  {
    id: '3',
    hashtag: '#BollywoodNews',
    posts: 6789,
    category: 'Entertainment',
  },
  {
    id: '4',
    hashtag: '#TechTwitter',
    posts: 5432,
    category: 'Technology',
  },
  {
    id: '5',
    hashtag: '#MumbaiRains',
    posts: 4321,
    category: 'Weather',
  },
];